# Generated by Django 4.2.5 on 2023-09-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_classroom', '0002_alter_customuser_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Class Representative', 'Class Representative')], default='Student', max_length=200),
        ),
    ]
