# Generated by Django 4.2.5 on 2023-09-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_classroom', '0003_authcode_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day_taught',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
