# Generated by Django 4.2.5 on 2023-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_classroom', '0004_course_day_taught_course_from_time_course_to_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day_taught',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=200, null=True),
        ),
    ]
