# Generated by Django 4.2.5 on 2023-09-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_classroom', '0005_alter_course_day_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
