# Generated by Django 4.2.5 on 2023-09-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_classroom', '0006_customuser_status_customuser_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='student_class',
            field=models.ManyToManyField(blank=True, null=True, to='our_classroom.studentclass'),
        ),
        migrations.AlterField(
            model_name='course',
            name='day_taught',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200, null=True),
        ),
    ]
