# Generated by Django 4.2.5 on 2023-09-22 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('our_classroom', '0008_lecturer_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='our_classroom.studentclass'),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='our_classroom.studentclass'),
        ),
    ]
