# Generated by Django 4.2.5 on 2023-09-25 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('our_classroom', '0010_alter_course_day_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
